### ISSUE TITLE
Re-publish to Gradle Plugin Portal

### ISSUE THREAD

**Issue by timyates** [IntershopCommunicationsAG/scmversion-gradle-plugin#26]
Hiya!

I was doing a scan of the Gradle Plugin Portal and noticed that there is an issue with `3.1.0` (the latest version) of your plugin `com.intershop.gradle.scmversion`.

https://plugins.gradle.org/plugin/com.intershop.gradle.scmversion

There was a [bug in versions prior to 0.9.7](https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573), where artifacts would silently not be pushed into the repo, which means the latest version of your plugin will not work properly when people apply it to their build.

I see you have [updated the plugin to `0.9.7`](https://github.com/IntershopCommunicationsAG/scmversion-gradle-plugin/commit/cc6bd07b62f77a25f84229fd2dd12cb037fc265c) (though `0.9.9`  is the latest), but to get a working plugin in the Portal, you will need to re-publish a new version.

If you want, I can then remove the broken `3.1.0` from the Portal

Thanks (and sorry about that).

Let us know here [or in the forums](https://discuss.gradle.org/c/help-discuss/plugin-portal) if you need more assistance.

Cheers,

Tim

**Comment by m-raab** [comment]
new versions were created
