### ISSUE TITLE
On jenkins version calculation is buggy when moving from 2.5.5 to 2.6.0

### ISSUE THREAD

**Issue by f3rdy** [IntershopCommunicationsAG/scmversion-gradle-plugin#48]
Hi Matthias,

we're using Jenkins to calculate the version using scm-versioning plugin on one of our intershop project. Since 2.6.0 the calculation introduces the revisionId into the version string:

```
$ ./gradlew -PrunOnCI=true showVersion -d | grep Version

[snip]

10:51:18.802 [WARN] [com.intershop.gradle.scm.extension.VersionExtension] All tasks will be executed on a CI build environment.
10:51:20.093 [WARN] [com.intershop.gradle.scm.services.git.GitVersionService] It is not possible to identify the correct version. The default value 3.0.0.0 will be used
10:51:20.219 [INFO] [com.intershop.gradle.scm.services.git.GitVersionService] Version analysis: Path: c16a629fae543da34e6274d680b530ba43aa3971, version: 3.0.0.0-c16a629fae543da34e6274d680b530
ba43aa3971, changed: true, metadata: , fromBranch: false, default: true
10:51:20.221 [INFO] [com.intershop.gradle.scm.services.git.GitVersionService] Version 3.0.0.0 will be extended with SNAPSHOT

[snip]

10:51:32.941 [DEBUG] [com.intershop.gradle.scm.task.ShowVersion] Version is 3.0.0.0-c16a629fae543da34e6274d680b530ba43aa3971-SNAPSHOT
```

While I can't reproduce it locally where the same call on the cloned repository results to 3.0.0.0-SNAPSHOT correctly, this may has to do with the jenkins cloning of the sources.

Any suggestions where to look?

**Comment by m-raab** [comment]
The name of the brach is the hash (path name) and not a name like master or any other branch name. It seems that the Jenkins Git plugin runs a very special checkout.

**Comment by m-raab** [comment]
We removed a configuration / limitation for branch names as an extension for the version. This will help to handle feature branches much more easily. That means that branch name is always added to version as long the name starts with the feature branch extension. If there is no configured prefix and the branch name is not "master" the branch name is used as it is.
I don't know how Jenkins handle the repository clone and checkout. But you can check the branch name of your working copy with 'git branch'. This should show the branch name.
