### ISSUE TITLE
Releases from Hotfix or Bugfix-Branches

### ISSUE THREAD

**Issue by f3rdy** [IntershopCommunicationsAG/scmversion-gradle-plugin#62]
Is it possible to create releases from hotfix or bugfix branches?

We have the following configuration:

```
scm {
    version {
        type = 'fourDigits'
        increment = 'PATCH'
        patternDigits = 1
        initialVersion = '1.0.0.0'
        branchWithVersion = true
        majorVersionOnly = false
    }
}
```

We have a simple test project, where we commit to master as a main release branch. We can do a tag of, say `RELEASE_1.0.0.0` and a release version 1.0.0.0 is created. Perfect. Further commits into the master will lead to snapshot releases versioned with `1.0.1.0-SNAPSHOT`. Perfect too.

Now we find out about a bug we introduced in `RELEASE_1.0.0.0`. So we create a hotfix branch `HB_1.0.0.1-hotfixes` (since, when we name it `HB_1.0.0.1` only, the snapshot versions to be build from that HB branch will look like `1.0.0.1-ull-SNAPSHOT`). The origin for the hotfix branch is the RELEASE_1.0.0.0 tag.

Now, we want to release the hotfix. Creating a tag named `RELEASE_1.0.0.1` from the `HB_1.0.0.1-hotfixes` branch results in:

```
It is not possible to identify the correct version. The default value 1.0.0.0 will be used
Version analysis: Path: RELEASE_1.0.0.1, version: 1.0.0.0, changed: true, metadata: , fromBranch: false, default: true
Version 1.0.0.0 will be extended with SNAPSHOT
```

So, we try to suffix to the tag name according to the branch name:

```
Version from tag RELEASE_1.0.0.1-hotfixes
Version analysis: Path: RELEASE_1.0.0.1-hotfixes, version: 1.0.0.1-hotfixes, changed: false, metadata: , fromBranch: false, default: false
Version 1.0.0.1-hotfixes will be used without extension (No changes detected!).

----------------------------------------------
    Project version: 1.0.0.1-hotfixes
----------------------------------------------
```

There we have a release, but with the suffix `-hotfixes`.

Question here is, how to do it right. We want to have hotfix releases for a version 1.0.0.0, where the increment is in the last digit, say 1.0.0.1, 1.0.0.2, and we want them to be created from the hotfix branch.

Any suggestions?

**Comment by m-raab** [comment]
The first run has changes on the working copy - `changed: true` - version will be extended with SNAPSHOT - and the program can not find a tag on the existing branch - `It is not possible to identify the correct version.` - version is 1.0.0.0.

The second run has no changes on the working copy - `changed: false`.

The configuration should be changed to `increment = 'HOTFIX'`.

I can not find an issue, therefore I close this. If you have any suggestion for improvements, please feel free and send a patch for this plugin. You can create also a fork of this plugin and add your own features.
